'use strict'

module.exports = {
  'evergreen-alert': 'Alert',
  'evergreen-autocomplete': 'Autocomplete',
  'evergreen-avatar': 'Avatar',
  'evergreen-buttons': 'Button',
  'evergreen-checkbox': 'Checkbox',
  'evergreen-colors': 'colors',
  'evergreen-combobox': 'Combobox',
  'evergreen-corner-dialog': 'CornerDialog',
  'evergreen-dialog': 'Dialog',
  'evergreen-file-picker': 'FilePicker',
  'evergreen-form-field': 'FormField',
  'evergreen-image': 'Image',
  'evergreen-overlay': 'Overlay',
  'evergreen-popover': 'Popover',
  'evergreen-portal': 'Portal',
  'evergreen-positioner': 'Positioner',
  'evergreen-radio': 'Radio',
  'evergreen-search-input': 'SearchInput',
  'evergreen-segmented-control': 'SegmentedControl',
  'evergreen-select-menu': 'SelectMenu',
  'evergreen-select': 'Select',
  'evergreen-side-sheet': 'SideSheet',
  'evergreen-spinner': 'Spinner',
  'evergreen-switch': 'Switch',
  'evergreen-tabs': 'Tab',
  'evergreen-text-input': 'TextInput',
  'evergreen-textarea': 'Textarea',
  'evergreen-tooltip': 'Tooltip'
}
